version: "3.5"

services:
  postgres:
    image: postgres
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: metastore_db
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  # blob-storage:
  #   image: mcr.microsoft.com/azure-storage/azurite
  #   ports:
  #     - 10000:10000
  #   volumes:
  #   - ./azurite:/data
  #   container_name: blob-storage
  #   command: azurite-blob --blobHost 0.0.0.0
  #   healthcheck:
  #     test: ["CMD", "nc", "-zv", "localhost", "10000"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3

  hive-metastore:
    platform: linux/x86_64
    build: .
    image: hive-metastore:latest
    ports:
    - 9083:9083
    volumes:
    - ./scripts/entrypoint.sh:/entrypoint.sh
    - ./conf/metastore-site-azure.xml:/opt/apache-hive-metastore-3.1.3-bin/conf/metastore-site.xml
    container_name: hive-metastore
    depends_on:
      postgres:
        condition: service_healthy
      # blob-storage:
      #   condition: service_healthy